const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, AlignmentType, BorderStyle, ShadingType, ImageRun, Footer, PageNumber, VerticalAlign } = require("docx");
const FONT="Arial", PAGE_W=12240, PAGE_H=15840, MARGIN=1080, CW=PAGE_W-2*MARGIN, GRAY="D9D9D9";
const thin={style:BorderStyle.SINGLE,size:4,color:"808080"}, borders={top:thin,bottom:thin,left:thin,right:thin};
const t=(text,o={})=>new TextRun({text,font:FONT,size:20,...o});
const p=(ch,o={})=>new Paragraph({spacing:{after:100,line:264},...o,children:Array.isArray(ch)?ch:[t(ch)]});
const section=(x)=>new Paragraph({spacing:{before:200,after:80},border:{bottom:{style:BorderStyle.SINGLE,size:6,color:"000000",space:2}},children:[t(x,{bold:true,size:22})]});
const clause=(n,h,b,init=false)=>new Paragraph({spacing:{after:110,line:264},alignment:AlignmentType.JUSTIFIED,children:[t(`${n}. ${h}. `,{bold:true}),t(b),...(init?[t("   Renter initials: ______",{bold:true})]:[])]});
const cell=(text,w,shade=false)=>new TableCell({width:{size:w,type:WidthType.DXA},borders,margins:{top:60,bottom:60,left:100,right:100},verticalAlign:VerticalAlign.CENTER,...(shade?{shading:{type:ShadingType.CLEAR,fill:GRAY,color:"auto"}}:{}),children:[new Paragraph({spacing:{after:0},children:[t(text,shade?{bold:true,size:18}:{})]})]});
const c4=[2400,2640,2400,2640];
const tbl=(rows)=>new Table({width:{size:CW,type:WidthType.DXA},columnWidths:c4,rows:rows.map(r=>new TableRow({children:r.map((c,i)=>cell(c,c4[i],i%2===0))}))});
const logo=fs.readFileSync("card/nashco-logo.png");
const half=CW/2;
const sig=(l)=>[new Paragraph({spacing:{before:360,after:0},children:[t("______________________________________")]}),new Paragraph({spacing:{after:0},children:[t(l,{size:18})]})];
const doc=new Document({creator:"Nashco Rentals LLC",title:"Mulcher Attachment Addendum",styles:{default:{document:{run:{font:FONT,size:20}}}},sections:[{
 properties:{page:{size:{width:PAGE_W,height:PAGE_H},margin:{top:MARGIN,bottom:MARGIN,left:MARGIN,right:MARGIN}}},
 footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[t("Nashco Rentals LLC  |  Mulcher Addendum  |  Page ",{size:16,color:"666666"}),new TextRun({children:[PageNumber.CURRENT],font:FONT,size:16,color:"666666"}),t(" of ",{size:16,color:"666666"}),new TextRun({children:[PageNumber.TOTAL_PAGES],font:FONT,size:16,color:"666666"}),t("     Renter initials: ______",{size:16,color:"666666"})]})]})},
 children:[
  new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:120},children:[new ImageRun({type:"png",data:logo,transformation:{width:300,height:80}})]}),
  new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:40},children:[t("MULCHER ATTACHMENT ADDENDUM",{bold:true,size:30})]}),
  new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:200},children:[t("To the Nashco Rentals Skid Steer Rental Agreement dated ____________________   Agreement #: ____________",{size:18,italics:true,color:"444444"})]}),
  p([t("This Addendum is part of the Rental Agreement between Nashco Rentals LLC (\"Nashco\") and the Renter named in that Agreement. If this Addendum and the Agreement conflict, this Addendum controls for the mulcher attachment. All other terms of the Agreement remain in effect.")],{alignment:AlignmentType.JUSTIFIED}),
  section("1. ATTACHMENT"),
  tbl([["Attachment:","Takeuchi TUMLSSL150VT Forestry Mulcher","Serial #:","2600738"],["Replacement value:","$53,000","Carrier:","Takeuchi TL11R3 high-flow (per Agreement)"],["Teeth count OUT:","","Teeth count IN:",""],["Teeth damaged / missing at return:","","Charge per tooth:","$75 each, parts and labor"],["Named operator (print):","","Operator phone:",""]]),
  section("2. TERMS"),
  clause(1,"Experienced operators only","The Renter states that the named operator has run a hydraulic forestry mulcher on a skid steer or track loader before, understands its hazards, and has answered Nashco's screening questions truthfully. Only the named operator may run the machine while the mulcher is attached. No one else, no exceptions. Nashco may watch the operator run the mulcher at delivery and may cancel the rental on the spot, with a full refund of rent, if Nashco is not satisfied with how it is being run.",true),
  clause(2,"Safe operation","The operator will: keep the cab door closed and the seat belt fastened whenever the head is turning; keep everyone else at least 300 feet away, including behind the machine; work trees from the top down and never push over standing trees with the head; keep the head close to the ground and never raise a spinning head above the cab; never reach under, clear, or service the head with the machine running; and shut down immediately on any unusual vibration, noise, hydraulic leak, or smoke."),
  clause(3,"Prohibited use","The mulcher will not be run in or near rock, caliche, concrete, gravel, or riprap; on fence lines, T-posts, wire, cable, pipe, or any metal; on material larger than the head is rated for; in standing water; with the head raised above chest height; or by any operator other than the named operator. Ground contact with the teeth is a prohibited use unless Nashco has approved it in writing for the job.",true),
  clause(4,"Fire","Mulching creates fire risk. The Renter will keep a charged fire extinguisher on the machine and a water source at the job site, will not run the mulcher during a county burn ban or a Red Flag Warning, will stop work if smoke is seen coming from the head or debris, and will clear mulch and debris off the machine, belly pan, and engine compartment at least twice a day and before shutting down for the day. The Renter is responsible for any fire and any damage it causes."),
  clause(5,"Teeth, wear, and damage","Nashco will count and inspect the teeth with the Renter at delivery and at return and record both counts above. Teeth that are missing, broken, or worn past the carbide are not normal wear and will be charged at the per-tooth rate above. Damage to the rotor, bearings, motor, hoses, couplers, push bar, or housing is charged at Nashco's actual repair cost plus the daily rate for each day the mulcher is out of service, up to the replacement value above. Loss or destruction of the mulcher is charged at the replacement value.",true),
  clause(6,"Hydraulics","The mulcher runs only on the high-flow circuit. The Renter will keep the couplers clean, connect and disconnect only with the engine off and pressure relieved, check hydraulic fluid level daily, and stop immediately on any leak. Damage from running the head on the wrong circuit, on a low fluid level, or with a leak is the Renter's responsibility."),
  clause(7,"Deposit","The deposit for a rental that includes the mulcher is $2,500, in addition to any deposit under the Agreement, and is due before delivery. Nashco may apply it to any amount owed under this Addendum or the Agreement. The Renter remains responsible for any amount above the deposit."),
  clause(8,"Right to end the rental","If Nashco sees or learns of any breach of this Addendum, including a different operator on the seat, Nashco may end the rental and retake the machine and mulcher immediately, and the Renter will pay rent through the date of return plus all costs of retaking."),
  section("3. SIGNATURES"),
  p([t("By signing, the Renter confirms that the named operator has read this Addendum, that the answers given to Nashco's screening questions were true, and that the Renter accepts responsibility for the mulcher as described above.")],{alignment:AlignmentType.JUSTIFIED}),
  new Table({width:{size:CW,type:WidthType.DXA},columnWidths:[half,half],rows:[new TableRow({children:[
   new TableCell({width:{size:half,type:WidthType.DXA},borders:{top:{style:BorderStyle.NONE,size:0,color:"FFFFFF"},bottom:{style:BorderStyle.NONE,size:0,color:"FFFFFF"},left:{style:BorderStyle.NONE,size:0,color:"FFFFFF"},right:{style:BorderStyle.NONE,size:0,color:"FFFFFF"}},margins:{right:200},children:[...sig("Nashco Rentals LLC, by (signature)"),...sig("Date")]}),
   new TableCell({width:{size:half,type:WidthType.DXA},borders:{top:{style:BorderStyle.NONE,size:0,color:"FFFFFF"},bottom:{style:BorderStyle.NONE,size:0,color:"FFFFFF"},left:{style:BorderStyle.NONE,size:0,color:"FFFFFF"},right:{style:BorderStyle.NONE,size:0,color:"FFFFFF"}},margins:{left:200},children:[...sig("Renter signature"),...sig("Named operator signature (if different)"),...sig("Date")]})]})]}),
  p([t("Nashco Rentals LLC  ·  Leona, Texas  ·  903-644-1122  ·  heath@rentnashco.com",{size:16,color:"666666"})],{alignment:AlignmentType.CENTER,spacing:{before:300}}),
 ]}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("Nashco_Mulcher_Addendum.docx",b);console.log("written");});
